"""Permission bitfield for chat servers (Stage-1 control plane)."""

VIEW_CHANNEL = 1 << 0
SEND_MESSAGES = 1 << 1
MANAGE_MESSAGES = 1 << 2
MANAGE_CHANNELS = 1 << 3
MANAGE_SERVER = 1 << 4
BAN_MEMBERS = 1 << 5
KICK_MEMBERS = 1 << 6
ADMINISTRATOR = 1 << 7
CREATE_INVITE = 1 << 8

ALL = (
    VIEW_CHANNEL
    | SEND_MESSAGES
    | MANAGE_MESSAGES
    | MANAGE_CHANNELS
    | MANAGE_SERVER
    | BAN_MEMBERS
    | KICK_MEMBERS
    | ADMINISTRATOR
    | CREATE_INVITE
)

DEFAULT_EVERYONE = VIEW_CHANNEL | SEND_MESSAGES | CREATE_INVITE
