# Generated by Django 5.2.17 on 2026-09-14 12:35

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('kind', models.CharField(blank=True, max_length=32)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='worlds.location')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('premise', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('invite_only', 'Invite Only')], default='public', max_length=16)),
                ('content_rating', models.CharField(blank=True, max_length=32)),
                ('world_time', models.DateTimeField()),
                ('tick_interval', models.DurationField(default=datetime.timedelta(days=1))),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('simulation_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_worlds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('capability_codes', models.JSONField(blank=True, default=list)),
                ('starter_relations', models.JSONField(blank=True, default=list)),
                ('starter_knowledge', models.JSONField(blank=True, default=list)),
                ('max_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('invite_only', models.BooleanField(default=False)),
                ('starter_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='worlds.location')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_templates', to='worlds.world')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='worlds.world'),
        ),
        migrations.CreateModel(
            name='WorldMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('left', 'Left'), ('banned', 'Banned')], default='active', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invite_ref', models.CharField(blank=True, max_length=64)),
                ('safety_state', models.CharField(blank=True, max_length=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='world_memberships', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='worlds.world')),
            ],
        ),
        migrations.AddConstraint(
            model_name='world',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'live', 'paused', 'archived'])), name='world_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='world',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'invite_only'])), name='world_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='roletemplate',
            constraint=models.UniqueConstraint(fields=('world', 'name'), name='role_name_per_world'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='location_slug_per_world'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='location_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='worldmembership',
            constraint=models.UniqueConstraint(fields=('world', 'account'), name='one_membership_per_account_world'),
        ),
    ]
