# Generated by Django 5.2.17 on 2026-09-15 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldSequence',
            fields=[
                ('world', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sequence', serialize=False, to='worlds.world')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(max_length=128)),
                ('actor_type', models.CharField(max_length=32)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('cause_type', models.CharField(blank=True, max_length=64)),
                ('cause_ref', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('delivery_state', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_event', to='audit.auditrecord')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='worlds.world')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('delivery_state', 'pending')), fields=['created_at'], name='outbox_pending_created_idx'), models.Index(fields=['world', 'created_at'], name='outbox_world_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('world', 'idempotency_key'), name='outbox_idempotency_per_world'), models.UniqueConstraint(fields=('world', 'sequence'), name='outbox_sequence_per_world'), models.CheckConstraint(condition=models.Q(('delivery_state__in', ['pending', 'delivered', 'failed'])), name='outbox_delivery_state_valid')],
            },
        ),
    ]
