# Generated by Django 5.2.17 on 2026-09-15 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(max_length=128)),
                ('actor_type', models.CharField(max_length=32)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('cause_type', models.CharField(blank=True, max_length=64)),
                ('cause_ref', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='worlds.world')),
            ],
            options={
                'indexes': [models.Index(fields=['world', 'created_at'], name='audit_world_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('world', 'idempotency_key'), name='audit_idempotency_per_world'), models.UniqueConstraint(fields=('world', 'sequence'), name='audit_sequence_per_world')],
            },
        ),
    ]
