# Generated by Django 5.2.17 on 2026-09-15 05:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('worlds', '0002_alter_world_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_proposition', models.TextField()),
                ('subject_refs', models.JSONField(blank=True, default=list)),
                ('origin_type', models.CharField(choices=[('direct_observation', 'Direct Observation'), ('message', 'Message'), ('media', 'Media'), ('document', 'Document'), ('inference', 'Inference'), ('rumor', 'Rumor'), ('ai_npc', 'Ai Npc'), ('system', 'System'), ('mutation', 'Mutation')], max_length=32)),
                ('origin_ref', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='worlds.world')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(blank=True, default='', max_length=512)),
                ('media_type', models.CharField(blank=True, default='text/plain', max_length=128)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('integrity_hash', models.CharField(blank=True, default='', max_length=128)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('confidential', 'Confidential'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=16)),
                ('chain_of_custody', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='characters.character')),
                ('owner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='organizations.organization')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='worlds.world')),
            ],
            options={
                'verbose_name_plural': 'evidence',
            },
        ),
        migrations.CreateModel(
            name='ClaimEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('context', 'Context')], max_length=16)),
                ('assessment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='knowledge.claim')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_links', to='knowledge.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_type', models.CharField(max_length=64)),
                ('subject_ref', models.CharField(max_length=200)),
                ('predicate', models.CharField(max_length=200)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('system_confidence', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('system_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('retracted', 'Retracted')], default='active', max_length=16)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('secret', 'Secret'), ('top_secret', 'Top Secret')], default='secret', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='worlds.world')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='linked_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='knowledge.fact'),
        ),
        migrations.CreateModel(
            name='KnowledgeEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awareness', models.CharField(choices=[('unaware', 'Unaware'), ('aware', 'Aware')], default='aware', max_length=16)),
                ('stance', models.CharField(choices=[('accepts', 'Accepts'), ('suspects', 'Suspects'), ('uncertain', 'Uncertain'), ('rejects', 'Rejects'), ('knows_false', 'Knows False')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('source_type', models.CharField(choices=[('direct_observation', 'Direct Observation'), ('message', 'Message'), ('media', 'Media'), ('document', 'Document'), ('inference', 'Inference'), ('rumor', 'Rumor'), ('ai_npc', 'Ai Npc')], max_length=32)),
                ('source_ref', models.CharField(blank=True, default='', max_length=200)),
                ('shareability', models.CharField(choices=[('private', 'Private'), ('confidential', 'Confidential'), ('off_record', 'Off Record'), ('shareable', 'Shareable'), ('public', 'Public')], default='private', max_length=16)),
                ('verification', models.CharField(choices=[('unverified', 'Unverified'), ('corroborated', 'Corroborated'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('debunked', 'Debunked')], default='unverified', max_length=16)),
                ('acquired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_edges', to='knowledge.claim')),
                ('owner_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_edges', to='characters.character')),
                ('owner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_edges', to='organizations.organization')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_edges', to='worlds.world')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_ref', models.CharField(max_length=200)),
                ('to_ref', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('message', 'Message'), ('post', 'Post'), ('leak', 'Leak'), ('publish', 'Publish'), ('rumor', 'Rumor'), ('other', 'Other')], max_length=16)),
                ('source_object_id', models.CharField(blank=True, default='', max_length=200)),
                ('transmitted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resulting_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transmissions', to='knowledge.claim')),
                ('source_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_transmissions', to='knowledge.claim')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='worlds.world')),
            ],
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['world', 'created_at'], name='evidence_world_created'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['owner_character', 'created_at'], name='evidence_owner_char'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_character__isnull', False), ('owner_organization__isnull', True)), models.Q(('owner_character__isnull', True), ('owner_organization__isnull', False)), _connector='OR'), name='evidence_xor_owner'),
        ),
        migrations.AddConstraint(
            model_name='claimevidencelink',
            constraint=models.UniqueConstraint(fields=('claim', 'evidence', 'relation'), name='claim_evidence_relation_unique'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['world', 'valid_from'], name='fact_world_valid_from'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['world', 'subject_ref'], name='fact_world_subject'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['world', 'created_at'], name='claim_world_created'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['world', 'status'], name='claim_world_status'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['owner_character', '-acquired_at'], name='ke_owner_char_acquired'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['owner_organization', '-acquired_at'], name='ke_owner_org_acquired'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['claim', 'owner_character'], name='ke_claim_owner_char'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['world', 'verification'], name='ke_world_verification'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeedge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_character__isnull', False), ('owner_organization__isnull', True)), models.Q(('owner_character__isnull', True), ('owner_organization__isnull', False)), _connector='OR'), name='knowledge_edge_xor_owner'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeedge',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_character__isnull', False)), fields=('claim', 'owner_character'), name='knowledge_edge_unique_character'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeedge',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_organization__isnull', False)), fields=('claim', 'owner_organization'), name='knowledge_edge_unique_org'),
        ),
        migrations.AddIndex(
            model_name='transmission',
            index=models.Index(fields=['world', 'transmitted_at'], name='tx_world_transmitted'),
        ),
        migrations.AddIndex(
            model_name='transmission',
            index=models.Index(fields=['source_claim'], name='tx_source_claim'),
        ),
        migrations.AddIndex(
            model_name='transmission',
            index=models.Index(fields=['resulting_claim'], name='tx_resulting_claim'),
        ),
    ]
