# Generated by Django 5.2.17 on 2026-09-15 05:06

import apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigIntegerField(default=apps.chat.models._snowflake_default, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_key', models.CharField(blank=True, max_length=255)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('flags', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_chat_servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigIntegerField(default=apps.chat.models._snowflake_default, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.BigIntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('hoist', models.BooleanField(default=False)),
                ('mentionable', models.BooleanField(default=False)),
                ('is_everyone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='chat.server')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='chat.role')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.server')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.server')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigIntegerField(default=apps.chat.models._snowflake_default, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.SmallIntegerField(choices=[(0, 'Text'), (1, 'Dm'), (2, 'Voice'), (3, 'Group Dm'), (4, 'Category'), (5, 'Announcement')], default=0)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('topic', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('nsfw', models.BooleanField(default=False)),
                ('rate_limit_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='chat.channel')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='chat.server')),
            ],
        ),
        migrations.CreateModel(
            name='ServerBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='chat.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_bans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('flags', models.BigIntegerField(default=0)),
                ('timeout_until', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPermissionOverwrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('role', 'Role'), ('member', 'Member')], max_length=16)),
                ('target_id', models.BigIntegerField()),
                ('allow', models.BigIntegerField(default=0)),
                ('deny', models.BigIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overwrites', to='chat.channel')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('target_type', 'role')), fields=('channel', 'target_type', 'target_id'), name='chat_overwrite_role_unique'), models.UniqueConstraint(condition=models.Q(('target_type', 'member'), ('target_user__isnull', False)), fields=('channel', 'target_user'), name='chat_overwrite_member_unique')],
            },
        ),
        migrations.CreateModel(
            name='DmParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_participants', to='chat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'channel'], name='chat_dm_by_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'user'), name='chat_dm_participant_unique')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigIntegerField(default=apps.chat.models._snowflake_default, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('flags', models.BigIntegerField(default=0)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.channel')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', '-id'], name='chat_messages_timeline_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chat.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='chat_read_state_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['server', '-position'], name='chat_roles_server_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberrole',
            constraint=models.UniqueConstraint(fields=('server', 'user', 'role'), name='chat_member_role_unique'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['server', 'position', 'id'], name='chat_channels_server_idx'),
        ),
        migrations.AddConstraint(
            model_name='serverban',
            constraint=models.UniqueConstraint(fields=('server', 'user'), name='chat_ban_unique'),
        ),
        migrations.AddIndex(
            model_name='servermember',
            index=models.Index(fields=['user', 'server'], name='chat_members_user_idx'),
        ),
        migrations.AddIndex(
            model_name='servermember',
            index=models.Index(fields=['server', '-joined_at'], name='chat_members_joined_idx'),
        ),
        migrations.AddConstraint(
            model_name='servermember',
            constraint=models.UniqueConstraint(fields=('server', 'user'), name='chat_member_per_server'),
        ),
    ]
