# Generated by Django 5.2.17 on 2026-09-14 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=16)),
                ('public_profile', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='worlds.location')),
                ('role_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='worlds.roletemplate')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='worlds.world')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('world', 'account'), name='one_character_per_account_world')],
            },
        ),
    ]
