# Generated by Django 5.2.17 on 2026-09-15 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('worlds', '0002_alter_world_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_type', models.CharField(choices=[('government', 'Government'), ('company', 'Company'), ('newsroom', 'Newsroom'), ('science', 'Science'), ('faction', 'Faction'), ('ngo', 'Ngo'), ('intelligence', 'Intelligence'), ('guild', 'Guild'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('public_profile', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disbanded', 'Disbanded')], default='active', max_length=16)),
                ('max_leaders', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='worlds.location')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='worlds.world')),
            ],
        ),
        migrations.CreateModel(
            name='OrgInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='member', max_length=64)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_invitations', to='characters.character')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='characters.character')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='member', max_length=64)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to='characters.character')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('world', 'slug'), name='org_slug_per_world'),
        ),
        migrations.AddConstraint(
            model_name='orginvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True)), fields=('organization', 'character'), name='one_open_org_invite_per_character'),
        ),
        migrations.AddConstraint(
            model_name='orgmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'character'), name='one_org_membership_per_character'),
        ),
    ]
